import Image from "next/image"

export default function MobilityshowAlbum() {
    return (
        <>
            <h1>Album</h1>
            <Image
                src="/tokyo_mobility_show/mobility_show1.jpg"
                alt="mobility_show1"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show2.jpg"
                alt="mobility_show2"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show3.jpg"
                alt="mobility_show3"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show4.jpg"
                alt="mobility_show4"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show5.jpg"
                alt="mobility_show5"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show6.jpg"
                alt="mobility_show6"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show7.jpg"
                alt="mobility_show7"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show8.jpg"
                alt="mobility_show8"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show9.jpg"
                alt="mobility_show9"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show10.jpg"
                alt="mobility_show10"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show11.jpg"
                alt="mobility_show11"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show12.jpg"
                alt="mobility_show12"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show13.jpg"
                alt="mobility_show13"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show14.jpg"
                alt="mobility_show14"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show15.jpg"
                alt="mobility_show15"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show16.jpg"
                alt="mobility_show16"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show17.jpg"
                alt="mobility_show17"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show18.jpg"
                alt="mobility_show18"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show19.jpg"
                alt="mobility_show19"
                width={400}
                height={400}
            />
            <Image
                src="/tokyo_mobility_show/mobility_show20.jpg"
                alt="mobility_show20"
                width={400}
                height={400}
            />
        </>
    )
}